version: 2

conda:
  environment: .rtd-env-py3.yml

python:
  install:
    - method: pip
      path: .

build:
    jobs:
        pre_build: |
            python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py
